### ISSUE TITLE
TwoValuesCostProcessor throws  java.lang.ArithmeticException: Division by zero

### ISSUE THREAD

**Issue by cezarcoca** [cezarcoca/sonar-toxicity-chart#2]
For very big files the following exception is thrown : 
 Caused by: java.lang.ArithmeticException: Division by zero
at java.math.BigDecimal.divide(BigDecimal.java:1669)
at org.sonar.plugins.toxicity.debts.cost.TwoValuesCostProcessor.getCost(TwoValuesCostProcessor.java:46)
at org.sonar.plugins.toxicity.DebtsFilter.filter(DebtsFilter.java:70)
at org.sonar.plugins.toxicity.ToxicityChartDecorator.decorate(ToxicityChartDecorator.java:67)
at org.sonar.batch.phases.DecoratorsExecutor.executeDecorator(DecoratorsExecutor.java:85)

**Comment by cezarcoca** [comment]
Fixed in version 1.0
